### ISSUE TITLE
consider auto-detecting luajit

### ISSUE THREAD

**Issue by mralusw** [gustavo-hms/luar#19]
&hellip; this requires only
```
decl str luar_interpreter %sh{command -v luajit || command -v lua}
```

**Comment by gustavo-hms** [comment]
Thanks for the suggestion! I thought a bit about it and concluded that, at first, it's a handy feature. But, when you think about its implications, it may introduce some unexpected behaviour.

Consider, for instance, that the user has an script that uses the `utf8` library. It's built-in in Lua 5.4, but it's not present in Luajit. It may be the case that the script works normally until the user installs Luajit for some unrelated work and, suddenly, the script stops working. It would be counterintuitive and may lead to some hard debugging time for the user.

**Comment by mralusw** [comment]
Sure, your call.

I saw your comments on Kakoune discuss and thought you wanted to "prefer" `luajit` *if present*.

**Comment by gustavo-hms** [comment]
Actually, I'm currently using `luajit`, but it's because of some very large directory structures that [peneira](https://github.com/gustavo-hms/peneira) needs to filter in may daily usage. Before that, I didn't find the need for it.

In any case, it seems that, from the point of view of a general user, auto-detecting `luajit` could introduce some problems.

But I must say I liked your suggestion  and I'm considering using it to set the option in my `kakrc`:

```kak
set-option global luar_interpreter %sh{command -v luajit || command -v lua}
```

So, thank you again for suggesting it.

May I close this issue?

**Comment by mralusw** [comment]
Oh yeah sure &mdash; I didn't know where else to suggest this :)
