### ISSUE TITLE
Add a way to pass named parameters

### ISSUE THREAD

**Issue by alexherbo2** [gustavo-hms/luar#9]
It could be nice to access the arguments in the Lua block with a name instead of its position.

By the way, I do not fully understand why the client variable is not a list and why args is a function and not just a variable.

``` kak
lua %val{client} %{
  local client = args()
}
```

**Comment by gustavo-hms** [comment]
Hi, @alexherbo2!

Accessing with a name isn't straightforward, but I'm gonna think a bit to see if I can find a reasonable solution.

In the meantime, let me explain why it isn't obvious to implement and also why `args` is a function.

In the `README` I say a `lua %{}` block is like an anonymous function you can pass expansions to as arguments. Well, it's obviously a simplification for the plugin to be easily understandable. Under the hood, what happens is that all the arguments of the `:lua` command are redirected to the `luar.lua` script as command line arguments.

When, inside a `lua %{}` block we do something like this:
```lua
lua %val{client} %val{bufname} %{
    kak.echo(string.format("Editing %s in %s client", arg[2], arg[1]))
}
```
we are referencing this `arg` table<sup>[1]</sup> that is actually the array of the command line arguments passed to the `luar.lua` script. In Lua, the `arg` table is the equivalent of the `argv` array in C.

If all we have is the array of command line arguments, we can't easily guess the *meaning* of the values inside this array. Without understanding their meaning, we can't guess appropriate names to automatically bind them to variables. To be able to know what names the user expects from these arguments, we need to change the API somehow, allowing the user to describe the names she expects to find within the `lua %{}` block. And currently I can't think of an elegant way to do it.

Considering then that we can't know what names to bind to each argument, we also can't do something like this:
```lua
lua %val{client} %val{bufname} %{
    kak.echo(string.format("Editing %s in %s client", args.bufname, args.client))
}
```
because `args` can't guess what we mean by `bufname` and `client`.

So, what the `args` function really does?

It relies on the fact that, in Lua, functions can return multiple values (like in Go for instance), and automatically split the `arg` table in as many values as the length of this table, returning all of them. For instance, suppose the `arg` table has these four values: `{17, 19, 21, 23}`. Then, executing the `args()` function will return these four values extracted from the `arg` table. It's handy for the user because now she can bind 4 variables at once:
```lua
first, second, third, fourth = args()
```
instead of doing it in 4 different steps:
```lua
first = arg[1]
second = arg[2]
third = arg[3]
fourth = arg[4]
```

> I do not fully understand why the client variable is not a list

In Kakoune, `%val{client}` is the name of the current client, so it's always a single value, never a list. But if you do
```lua
lua %val{buflist} %{
    return #arg
}
```
then it will echo a number bigger than one<sup>[2]</sup>, meaning the `%val{buflist}` was passed as a list.

---

[1]: *Tables* are the sole data structure of Lua. They are used both as arrays and as dictionaries. In the specific case of the `arg` table, you can think of it as an array.
[2]: In Lua, the `#` operator returns the length of the table. So, `#arg` returns the number of the arguments passed to the `lua %{}` block.

**Comment by gustavo-hms** [comment]
Hi, @alexherbo2 ! 

I've experimented with some ways to get named parameters but none as simple as the `args` function. The experiments included adding switches in the `lua` command to allow the user to specify the names she expects, and also some obscure Lua meta-programming tricks, but in either way the user needs to somehow inform me her intentions in advance to allow me to bind the right names in the code.

At the end, I think the `args` function is the best option I could reach to the moment. I'm closing this issue, but I'll continue trying other designs in the hope to find the best possible one. I'm also open to suggestions. So feel free to reopen this issue if you have some neat idea.

**Comment by alexherbo2** [comment]
Yep it is not easy, especially with named list values.

**Comment by alexherbo2** [comment]
I wonder about the typing, you have no way to know it, no?

``` kak
lua %opt{my_plugin_enabled} %{
  -- Arguments
  local my_plugin_enabled = args()

  -- Test whether the plugin is enabled
  if my_plugin_enabled then
    return true
  end
}
```

**Comment by gustavo-hms** [comment]
> you have no way to know it, no?

Actually, I do. The plugin is already parsing the arguments: https://github.com/gustavo-hms/luar/blob/bb15470668eb6566995c75a25498decdd28dee85/luar.lua#L49-L57

It first try to convert the argument to a boolean, then to a number and then fallback to string.

You can see it in action in some places, like here: https://github.com/gustavo-hms/enluarada/blob/4fd6d6ce4eea58c67de6b271e758c078dd67dfda/search-tools/search-tools.kak#L31-L37

Note how the `on` variable is being tested as a boolean, and then, on line 37, it's subject to a boolean operation (the `not` operator).

If you type something like this in the command prompt:
```lua
lua 3 5 'return arg[1] + arg[2]'
```
You will see it printing `8` in the prompt. So, both `arg[1]` and `arg[2]` are being converted to Lua numbers.
